## Configuration Settings (Crucial for Bitstream Generation)
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

## Clock signal (100 MHz)
set_property PACKAGE_PIN W5 [get_ports clk100]							
set_property IOSTANDARD LVCMOS33 [get_ports clk100]
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk100]

## Reset Button (btnC)
set_property PACKAGE_PIN U18 [get_ports btnC]						
set_property IOSTANDARD LVCMOS33 [get_ports btnC]

## Switches (Filter Selection)
set_property PACKAGE_PIN V17 [get_ports {sw[0]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property PACKAGE_PIN V16 [get_ports {sw[1]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property PACKAGE_PIN W16 [get_ports {sw[2]}]					
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]

## VGA Connector
set_property PACKAGE_PIN G19 [get_ports {vga_r[0]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property PACKAGE_PIN H19 [get_ports {vga_r[1]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property PACKAGE_PIN J19 [get_ports {vga_r[2]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property PACKAGE_PIN N19 [get_ports {vga_r[3]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property PACKAGE_PIN N18 [get_ports {vga_b[0]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property PACKAGE_PIN L18 [get_ports {vga_b[1]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property PACKAGE_PIN K18 [get_ports {vga_b[2]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property PACKAGE_PIN J18 [get_ports {vga_b[3]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property PACKAGE_PIN J17 [get_ports {vga_g[0]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property PACKAGE_PIN H17 [get_ports {vga_g[1]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property PACKAGE_PIN G17 [get_ports {vga_g[2]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property PACKAGE_PIN D17 [get_ports {vga_g[3]}]				
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property PACKAGE_PIN P19 [get_ports vga_hsync]						
set_property IOSTANDARD LVCMOS33 [get_ports vga_hsync]
set_property PACKAGE_PIN R19 [get_ports vga_vsync]						
set_property IOSTANDARD LVCMOS33 [get_ports vga_vsync]

## Camera Data Bus
set_property PACKAGE_PIN P17 [get_ports {ov7670_d[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_d[0]}]
set_property PACKAGE_PIN N17 [get_ports {ov7670_d[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_d[1]}]
set_property PACKAGE_PIN M19 [get_ports {ov7670_d[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_d[2]}]
set_property PACKAGE_PIN M18 [get_ports {ov7670_d[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_d[3]}]
set_property PACKAGE_PIN L17 [get_ports {ov7670_d[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_d[4]}]
set_property PACKAGE_PIN K17 [get_ports {ov7670_d[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_d[5]}]
set_property PACKAGE_PIN C16 [get_ports {ov7670_d[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_d[6]}]
set_property PACKAGE_PIN B16 [get_ports {ov7670_d[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ov7670_d[7]}]

## Camera Control Signals
set_property PACKAGE_PIN A17 [get_ports ov7670_href]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_href]
set_property PACKAGE_PIN A16 [get_ports ov7670_pclk]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_pclk]
set_property PACKAGE_PIN R18 [get_ports ov7670_pwdn]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_pwdn]
set_property PACKAGE_PIN P18 [get_ports ov7670_reset]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_reset]
set_property PACKAGE_PIN A14 [get_ports ov7670_scl]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_scl]
set_property PACKAGE_PIN A15 [get_ports ov7670_sda]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_sda]
set_property PACKAGE_PIN B15 [get_ports ov7670_vsync]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_vsync]
set_property PACKAGE_PIN C15 [get_ports ov7670_xclk]
set_property IOSTANDARD LVCMOS33 [get_ports ov7670_xclk]

set_property PACKAGE_PIN U16 [get_ports {led0}]					
set_property IOSTANDARD LVCMOS33 [get_ports {led0}]

## Additional Camera Settings
set_property PULLUP TRUE [get_ports ov7670_scl]
set_property PULLUP TRUE [get_ports ov7670_sda]

## Allow PCLK to use non-dedicated clock routing (Standard for OV7670/Basys3)
set_property CLOCK_DEDICATED_ROUTE FALSE [get_nets ov7670_pclk_IBUF]